<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

namespace Sample\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Sample.Model.Response</code>
 */
class Response extends \Google\Protobuf\Internal\Message
{
    /**
     *错误码, http请求失败时大于0
     *
     * Generated from protobuf field <code>int32 errCode = 1;</code>
     */
    private $errCode = 0;
    /**
     *错误具体信息
     *
     * Generated from protobuf field <code>string errMsg = 2;</code>
     */
    private $errMsg = '';
    /**
     * Generated from protobuf field <code>map<string, string> data = 3;</code>
     */
    private $data;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $errCode
     *          错误码, http请求失败时大于0
     *     @type string $errMsg
     *          错误具体信息
     *     @type array|\Google\Protobuf\Internal\MapField $data
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Response::initOnce();
        parent::__construct($data);
    }

    /**
     *错误码, http请求失败时大于0
     *
     * Generated from protobuf field <code>int32 errCode = 1;</code>
     * @return int
     */
    public function getErrCode()
    {
        return $this->errCode;
    }

    /**
     *错误码, http请求失败时大于0
     *
     * Generated from protobuf field <code>int32 errCode = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setErrCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->errCode = $var;

        return $this;
    }

    /**
     *错误具体信息
     *
     * Generated from protobuf field <code>string errMsg = 2;</code>
     * @return string
     */
    public function getErrMsg()
    {
        return $this->errMsg;
    }

    /**
     *错误具体信息
     *
     * Generated from protobuf field <code>string errMsg = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setErrMsg($var)
    {
        GPBUtil::checkString($var, True);
        $this->errMsg = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> data = 3;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     * Generated from protobuf field <code>map<string, string> data = 3;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setData($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->data = $arr;

        return $this;
    }

}

