<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto

namespace Sample\Model;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Sample.Model.UserList</code>
 */
class UserList extends \Google\Protobuf\Internal\Message
{
    /**
     *用户列表
     *
     * Generated from protobuf field <code>repeated .Sample.Model.User list = 1;</code>
     */
    private $list;
    /**
     *分页
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     */
    private $page = 0;
    /**
     *分页条数
     *
     * Generated from protobuf field <code>int32 limit = 3;</code>
     */
    private $limit = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Sample\Model\User[]|\Google\Protobuf\Internal\RepeatedField $list
     *          用户列表
     *     @type int $page
     *          分页
     *     @type int $limit
     *          分页条数
     * }
     */
    public function __construct($data = NULL) {
        \Sample\Model\GPBMetadata\User::initOnce();
        parent::__construct($data);
    }

    /**
     *用户列表
     *
     * Generated from protobuf field <code>repeated .Sample.Model.User list = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getList()
    {
        return $this->list;
    }

    /**
     *用户列表
     *
     * Generated from protobuf field <code>repeated .Sample.Model.User list = 1;</code>
     * @param \Sample\Model\User[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Sample\Model\User::class);
        $this->list = $arr;

        return $this;
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @return int
     */
    public function getPage()
    {
        return $this->page;
    }

    /**
     *分页
     *
     * Generated from protobuf field <code>int32 page = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPage($var)
    {
        GPBUtil::checkInt32($var);
        $this->page = $var;

        return $this;
    }

    /**
     *分页条数
     *
     * Generated from protobuf field <code>int32 limit = 3;</code>
     * @return int
     */
    public function getLimit()
    {
        return $this->limit;
    }

    /**
     *分页条数
     *
     * Generated from protobuf field <code>int32 limit = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setLimit($var)
    {
        GPBUtil::checkInt32($var);
        $this->limit = $var;

        return $this;
    }

}

