// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Response.proto

package Sample_Model

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Response struct {
	ErrCode              int32             `protobuf:"varint,1,opt,name=errCode,proto3" json:"errCode,omitempty"`
	ErrMsg               string            `protobuf:"bytes,2,opt,name=errMsg,proto3" json:"errMsg,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_2c4c7055b2f7bc3f, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *Response) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Response)(nil), "Sample.Model.Response")
	proto.RegisterMapType((map[string]string)(nil), "Sample.Model.Response.DataEntry")
}

func init() { proto.RegisterFile("Response.proto", fileDescriptor_2c4c7055b2f7bc3f) }

var fileDescriptor_2c4c7055b2f7bc3f = []byte{
	// 175 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x0b, 0x4a, 0x2d, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x09, 0x4e, 0xcc, 0x2d,
	0xc8, 0x49, 0xd5, 0xf3, 0xcd, 0x4f, 0x49, 0xcd, 0x51, 0x5a, 0xcd, 0xc8, 0xc5, 0x01, 0x53, 0x20,
	0x24, 0xc1, 0xc5, 0x9e, 0x5a, 0x54, 0xe4, 0x9c, 0x9f, 0x92, 0x2a, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1,
	0x1a, 0x04, 0xe3, 0x0a, 0x89, 0x71, 0xb1, 0xa5, 0x16, 0x15, 0xf9, 0x16, 0xa7, 0x4b, 0x30, 0x29,
	0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x42, 0x26, 0x5c, 0x2c, 0x29, 0x89, 0x25, 0x89, 0x12, 0xcc,
	0x0a, 0xcc, 0x1a, 0xdc, 0x46, 0x0a, 0x7a, 0xc8, 0x66, 0xeb, 0xc1, 0x2d, 0x76, 0x49, 0x2c, 0x49,
	0x74, 0xcd, 0x2b, 0x29, 0xaa, 0x0c, 0x02, 0xab, 0x96, 0x32, 0xe7, 0xe2, 0x84, 0x0b, 0x09, 0x09,
	0x70, 0x31, 0x67, 0xa7, 0x56, 0x82, 0x2d, 0xe4, 0x0c, 0x02, 0x31, 0x85, 0x44, 0xb8, 0x58, 0xcb,
	0x12, 0x73, 0x4a, 0x53, 0xa1, 0x76, 0x41, 0x38, 0x56, 0x4c, 0x16, 0x8c, 0x49, 0x6c, 0x60, 0x2f,
	0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0x48, 0xc5, 0x23, 0x10, 0xd4, 0x00, 0x00, 0x00,
}
