<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GreeterService.proto

namespace Sample\Model\GPBMetadata;

class GreeterService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Sample\Model\GPBMetadata\User::initOnce();
        \Sample\Model\GPBMetadata\Response::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a81010a1447726565746572536572766963652e70726f746f120c53616d" .
            "706c652e4d6f64656c1a0e526573706f6e73652e70726f746f32430a0747" .
            "72656574657212380a0853617948656c6c6f12122e53616d706c652e4d6f" .
            "64656c2e557365721a162e53616d706c652e4d6f64656c2e526573706f6e" .
            "73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

