<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Response.proto

namespace Sample\Model\GPBMetadata;

class Response
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1010a0e526573706f6e73652e70726f746f120c53616d706c652e4d6f" .
            "64656c2288010a08526573706f6e7365120f0a07657272436f6465180120" .
            "012805120e0a066572724d7367180220012809122e0a0464617461180320" .
            "03280b32202e53616d706c652e4d6f64656c2e526573706f6e73652e4461" .
            "7461456e7472791a2b0a0944617461456e747279120b0a036b6579180120" .
            "012809120d0a0576616c75651802200128093a023801620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

