<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: User.proto

namespace Sample\Model\GPBMetadata;

class User
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a97020a0a557365722e70726f746f120c53616d706c652e4d6f64656c22" .
            "a7010a0455736572120a0a026964180120012803120c0a046e616d651802" .
            "20012809120e0a06617661746172180320012809120f0a07616464726573" .
            "73180420012809120e0a066d6f62696c6518052001280912280a03657874" .
            "18062003280b321b2e53616d706c652e4d6f64656c2e557365722e457874" .
            "456e7472791a2a0a08457874456e747279120b0a036b6579180120012809" .
            "120d0a0576616c75651802200128093a02380122490a08557365724c6973" .
            "7412200a046c69737418012003280b32122e53616d706c652e4d6f64656c" .
            "2e55736572120c0a0470616765180220012805120d0a056c696d69741803" .
            "20012805620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

